### ISSUE TITLE
6x6 Magnete ab 1.2 - Gründe und Befestigung

### ISSUE THREAD

**Issue by janschroeter** [nachdenksport/openlift#3]
Hi Simon,

in Version 1.2 hast du die Aufnahme für die Magnete in der Platte, laut Changelog, auf durchgängige Bohrungen geändert und 6x6 Magnete vorgesehen. Leider finden sich dort keine Informationen über die Gründe für diese Änderung. Kannst du diese ggf. etwas weiter erläutern? Auch konnte ich keine näheren Informationen über die dann vorgesehene Befestigung der Magnete in der Platte finden. Das Aufbau-Anleitungs-Video bezieht sich derzeit ja noch auf 1.1. Ich würde diese einfach einkleben, aber würde natürlich gern auch keine Fehler bei der Montage machen, welche sich durch einfaches Nachfragen vermeiden ließen.

Ich habe seit langer Zeit eine bisher unmontierte 1.1 Platte rumliegen und werde diese, vor dem nun endlich anstehenden Einbau, mit Montagebohrungen für die Absaugung versehen. Die Frage die sich mir stellt ist, ob ich auch gleich noch die Bohrungen für die Magnete in der Platte anpasse um sozusagen auf 1.3 zu aktualisieren.

MfG Jan

**Comment by nachdenksport** [comment]
Moin Jan,

die Bohrungen waren vorher Sacklöcher und beim Einkleben der Magnete gab es öfter Probleme, weil Luft zwischen Magnet und Bohrungsboden nicht entweichen konnte. Die Durchgangsbohrungen haben dieses Problem behoben. Ein weiterer Grund war, dass dadurch größere Magnete genutzt werden konnten mit mehr Haltekraft und im Reduzierring wiederum kleinere Magnete. Das hat ermöglicht das lästige Schleifen der Reduzierringe zu beseitigen. Die 6x6 Magnete werden seit den Durchgangsbohrungen auch nicht mehr mit Sekundenkleber, sondern mit hochfestem Schraubenkleber. Damit hat man mehrere Stunden Zeit die Position noch zu korrigieren und Fehler beim einkleben können eigentlich nicht mehr passieren.

Wenn du bei einer v1.1 Platte einfach ein kleines Loch in die 3 Sacklochbohrungen der Magnete bohrst hast du den gleichen Effekt, wie bei den aktuellen Platten. 1mm Durchmesser reicht schon.
